site_name: Profe Jorge
site_url: https://jorgelgpz.github.io/cursos/

nav:
    - Inicio: 'index.md'
    - Git: 'git/index.md'
    - Python:
      - 'python/index.md'
      - Manual:
        - 'python/manual/index.md'
        - Introducción a Python: 'python/manual/introduccion-python.md'
        - Tipos de Datos Primitivos Simples: 'python/manual/tipos-datos-simples.md'
        - Entrada y Salida por Terminal: 'python/manual/entrada-salida.md'
        - Condicionales: 'python/manual/condicionales.md'
        - Bucles: 'python/manual/bucles.md'
        - Listas: 'python/manual/listas.md'
        - Tuplas: 'python/manual/tuplas.md'
        - Diccionarios: 'python/manual/diccionarios.md'
        - Funciones: 'python/manual/funciones.md'
        - Programación funcional: 'python/manual/programacion-funcional.md'
        - Comprensión de Colecciones: 'python/manual/comprension-colecciones.md'
        - Ficheros: 'python/manual/ficheros.md'
        - Excepciones: 'python/manual/excepciones.md'
        - Programación Orientada a Objetos: 'python/manual/objetos.md'
        - Módulos: 'python/manual/modulos.md'
        - Filter: 'python/manual/filter.md'
        - Enumerate: 'python/manual/enumerate.md'
        - La librería Datetime: 'python/manual/datetime.md'
        - La librería Numpy: 'python/manual/numpy.md'
        - La librería Pandas: 'python/manual/pandas.md'
        - La librería Matplotlib: 'python/manual/matplotlib.md'
        - Depuración de código: 'python/manual/depuracion.md'
        - Referencias: 'python/manual/referencias.md'
      - Ejercicios:
        - 'python/ejercicios/index.md'
        - Tipos de Datos Simples: 'python/ejercicios/tipos-datos.md'
        - Cadenas: 'python/ejercicios/cadenas.md'
        - Condicionales: 'python/ejercicios/condicionales.md'
        - Bucles: 'python/ejercicios/bucles.md'
        - Listas y Tuplas: 'python/ejercicios/listas-tuplas.md'
        - Diccionarios: 'python/ejercicios/diccionarios.md'
        - Funciones: 'python/ejercicios/funciones.md'
        - Programación Funcional: 'python/ejercicios/programacion-funcional.md'
        - Ficheros: 'python/ejercicios/ficheros.md'
        - Depuración: 'python/ejercicios/depuracion.md'
        - Librería Pandas: 'python/ejercicios/pandas.md'
        - Librería Matplotlib: 'python/ejercicios/matplotlib.md'


theme:
  name: material
  favicon: images/favicon.png
  logo: assets/logo.jpg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - navigation.footer
    - content.code.copy
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      accent: purple
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # configuration for code
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true

extra:
  # Remove the footer display
  generator: false

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js